language: objective-c
osx_image: xcode8
rvm: 2.2

before_install:
   - sudo gem install cocoapods --no-ri --no-rdoc
   - pod repo update --silent

script: xcodebuild -workspace RxSample.xcworkspace -scheme RxSample -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' -sdk iphonesimulator test